### ISSUE TITLE
Navbar that pops up or fades in when scrolling down

### ISSUE THREAD

**Issue by AlessiaBaka** [AlessiaBaka/alessiabaka.github.io#14]

**Comment by AlessiaBaka** [comment]
Template per la scrolling nav 
https://blackrockdigital.github.io/startbootstrap-new-age/

**Comment by AlessiaBaka** [comment]
Fai conto che sia come questo però senza la navbar fixed sopra
https://www.creative-tim.com/product/get-shit-done-pro?affiliate_id=85444

**Comment by Eliijahh** [comment]
Ok perfect, it shouldn't be too difficult. As soon as I finish I can start helping, even just by reviewing the code you have been writing.

**Comment by AlessiaBaka** [comment]
Actually, for the second one, I've found the source code here on github! 

I'm talking about this: https://blackrockdigital.github.io/startbootstrap-new-age/

And the source you can look at is this: https://github.com/BlackrockDigital/startbootstrap-new-age

I'll study it and we'll see what comes out...

**Comment by Eliijahh** [comment]
Background color for the navbar: #dce6e6
