### ISSUE TITLE
Scrimia.html page tesi_cop1.jpg mancante

### ISSUE THREAD

**Issue by Eliijahh** [AlessiaBaka/alessiabaka.github.io#6]
L'immagine tesi_cop1.jpg non appare nel sito web nella pagina `scrimia.html`

<img width="1343" alt="screenshot 2017-07-25 16 46 32" src="https://user-images.githubusercontent.com/11465983/28580953-d514522a-7158-11e7-9324-6432754616c7.png">

**Comment by AlessiaBaka** [comment]
I've done it. Added the img on dev branch.
Should I delete this issue?

**Comment by Eliijahh** [comment]
Done
